import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { CalendarDays, Eye, Landmark, ReceiptText, Send, UsersRound } from "lucide-react";
import { useState } from "react";
import { SubHeader } from "@/components/app/SubHeader";
import { ConfirmPanel, ErrorNote, Field, SelectField } from "@/components/app/OpKit";
import { account, formatBRL } from "@/lib/mock-data";
import { addBeneficiary, postTx, useBalance } from "@/lib/bank";
import { parseAmount } from "@/lib/pix";

export const Route=createFileRoute("/app/transferencias")({component:Transferencias});
const banks=["237 — Banco Bradesco S.A.","001 — Banco do Brasil S.A.","341 — Itaú Unibanco S.A.","033 — Banco Santander (Brasil) S.A.","104 — Caixa Econômica Federal","260 — Nu Pagamentos S.A."] as const;
function formatDocument(value:string){const d=value.replace(/\D/g,"").slice(0,14);if(d.length<=11)return d.replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d{1,2})$/,"$1-$2");return d.replace(/(\d{2})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1/$2").replace(/(\d{4})(\d{1,2})$/,"$1-$2")}
function Transferencias(){
 const navigate=useNavigate();const balance=useBalance();const[name,setName]=useState("");const[doc,setDoc]=useState("");const[bank,setBank]=useState<string>(banks[0]);const[branch,setBranch]=useState("");const[acc,setAcc]=useState("");const[amount,setAmount]=useState("");const[date,setDate]=useState("");const[save,setSave]=useState(false);const[error,setError]=useState<string|null>(null);const[review,setReview]=useState(false);const[showBalance,setShowBalance]=useState(true);const value=parseAmount(amount);const internal=bank.startsWith("237");const type=internal?"Entre contas Bradesco":"TED para outro banco";
 const check=()=>{if(name.trim().length<3)return setError("Informe o nome do favorecido.");if(doc.replace(/\D/g,"").length<11)return setError("Informe um CPF ou CNPJ válido.");if(!/^\d{4}$/.test(branch))return setError("A agência deve ter 4 números.");if(acc.replace(/\D/g,"").length<4)return setError("Informe a conta com dígito.");if(!Number.isFinite(value)||value<=0)return setError("Informe um valor maior que zero.");if(!date&&value>balance)return setError("Saldo insuficiente.");setError(null);setReview(true)};
 const rows=[{label:"Tipo",value:type},{label:"Favorecido",value:name.trim().toUpperCase()},{label:"CPF/CNPJ",value:doc},{label:"Instituição",value:bank},{label:"Agência / Conta",value:`${branch} / ${acc}`},{label:"Quando",value:date?`Agendado para ${new Date(`${date}T12:00`).toLocaleDateString("pt-BR")}`:"Agora"}];
 const confirm=()=>{if(save)addBeneficiary({name:name.trim().toUpperCase(),doc,bank,branch,account:acc});const tx=postTx({category:"transferencia",kind:"out",title:date?"PIX AGENDADO":internal?"TRANSF. ENTRE CONTAS":"TED ENVIADA",counterpart:`PARA: ${name.trim().toUpperCase()}`,amount:value,channel:"App Empresas",status:date?"Agendado":"Concluído",...(date?{scheduledFor:new Date(`${date}T12:00`).toISOString()}:{}),extraRows:rows,notify:{kind:"transferencia",title:date?"Pix agendado":"Transferência enviada",body:`${formatBRL(value)} para ${name.trim().toUpperCase()}.`}});void navigate({to:"/app/comprovante/$id",params:{id:tx.id},replace:true})};
 if(review)return <><SubHeader title="Revisar transferência" compactActions/><ConfirmPanel verb="transferência" amount={value} rows={rows} onConfirm={confirm} onBack={()=>setReview(false)}/></>;
 return <><SubHeader title="Transferências" compactActions/><main className="bg-[#f4f5f7] px-3 pb-8 pt-4">
 <section className="rounded-xl border border-[#dedfe3] bg-white p-4 shadow-sm"><p className="text-[11px] font-bold uppercase tracking-wide text-muted-foreground">Conta de origem · ambiente simulado</p><p className="mt-2 text-sm font-bold">{account.company}</p><p className="mt-1 text-xs text-muted-foreground">CNPJ {account.cnpj}</p><div className="mt-4 grid grid-cols-[minmax(0,1fr)_auto] items-end gap-3 border-t border-border pt-4"><div><p className="text-sm text-muted-foreground">Saldo disponível</p><p className="mt-1 text-[clamp(1.65rem,8vw,2.2rem)] font-extrabold tabular-nums">{showBalance?formatBRL(balance):"R$ ••••••••"}</p></div><button type="button" onClick={()=>setShowBalance(v=>!v)} className="grid size-10 place-items-center rounded-full text-[#0057b8]"><Eye className="size-6"/></button></div><div className="mt-4 border-t border-border pt-3 text-sm font-medium"><Landmark className="mr-2 inline size-5 text-[#0057b8]"/>Conta corrente: {account.number} · Agência {account.branch}</div></section>
 <section className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={()=>document.getElementById("new-transfer")?.scrollIntoView({behavior:"smooth"})} className="flex min-h-14 items-center justify-center gap-3 rounded-lg border bg-white px-3 text-sm font-semibold"><Send className="size-5 text-[#0057b8]"/>Transferir</button><button type="button" onClick={()=>void navigate({to:"/app/agendamentos"})} className="flex min-h-14 items-center justify-center gap-3 rounded-lg border bg-white px-3 text-sm font-semibold"><CalendarDays className="size-5 text-[#0057b8]"/>Agendamentos</button><button type="button" onClick={()=>void navigate({to:"/app/favorecidos"})} className="flex min-h-14 items-center justify-center gap-3 rounded-lg border bg-white px-3 text-sm font-semibold"><UsersRound className="size-5 text-[#0057b8]"/>Meus favorecidos</button><button type="button" onClick={()=>void navigate({to:"/app/agendamentos"})} className="flex min-h-14 items-center justify-center gap-3 rounded-lg border bg-white px-3 text-sm font-semibold text-[#0057b8]"><ReceiptText className="size-5"/>Comprovantes</button></section>
 <section id="new-transfer" className="mt-3 rounded-xl border border-[#dedfe3] bg-white p-4 shadow-sm"><h2 className="text-lg font-bold">Dados da transferência</h2><div className="mt-3"><Field label="Beneficiário / Favorecido *" value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do favorecido"/><Field label="CPF ou CNPJ *" value={doc} onChange={e=>setDoc(formatDocument(e.target.value))} inputMode="numeric" placeholder="000.000.000-00"/><SelectField label="Banco *" options={banks} value={bank} onChange={e=>setBank(e.target.value)}/><div className="grid grid-cols-2 gap-3"><Field label="Agência *" value={branch} maxLength={4} onChange={e=>setBranch(e.target.value.replace(/\D/g,""))} inputMode="numeric" placeholder="0000"/><Field label="Conta *" value={acc} onChange={e=>setAcc(e.target.value)} placeholder="000000-0"/></div><Field label="Valor da transferência *" value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="R$ 0,00"/><Field label="Data da transferência" type="date" value={date} onChange={e=>setDate(e.target.value)}/><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={save} onChange={e=>setSave(e.target.checked)} className="size-4"/>Salvar como favorecido</label>{error&&<ErrorNote>{error}</ErrorNote>}<button type="button" onClick={check} className="mt-5 w-full rounded-md bg-[#cc092f] px-4 py-3 font-bold text-white">Continuar</button></div></section>
 <p className="mt-5 rounded-lg border border-dashed border-border bg-white p-3 text-center text-[11px] font-medium text-muted-foreground">AMBIENTE SIMULADO · SEM OPERAÇÕES BANCÁRIAS REAIS</p></main></>;
}