import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { CalendarDays, Eye, Landmark, ReceiptText, Repeat2, Send, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import { SubHeader } from "@/components/app/SubHeader";
import { ConfirmPanel, ErrorNote, Field, SelectField } from "@/components/app/OpKit";
import { account, formatBRL } from "@/lib/mock-data";
import { addBeneficiary, formatDay, postTx, useBalance, useBank } from "@/lib/bank";
import { parseAmount } from "@/lib/pix";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/app/transferencias")({ head:()=>({meta:[{title:"Transferências — Conta Empresas (simulado)"},{name:"description",content:"Transferências em ambiente de demonstração, sem operações bancárias reais."}]}), component:Transferencias });

const scheduledAmounts:Record<string,number>={"MARIA AUXILIADORA DE OLIVEIRA":5795202,"VIVIANI DE OLIVEIRA SOUZA":4130637,"JOSE RAUGI NETO":1894938,"KATIANE DE OLIVEIRA":4750423,"JOSÉ MARIA GOMES PEIXOTO":4130637};
function scheduledAmount(name:string){return scheduledAmounts[name]??3000000}
const banks=["237 — Banco Bradesco S.A.","001 — Banco do Brasil S.A.","341 — Itaú Unibanco S.A.","033 — Banco Santander (Brasil) S.A.","104 — Caixa Econômica Federal","260 — Nu Pagamentos S.A."] as const;
function formatDocument(value:string){const d=value.replace(/\D/g,"").slice(0,14);if(d.length<=11)return d.replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d{1,2})$/,"$1-$2");return d.replace(/(\d{2})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1/$2").replace(/(\d{4})(\d{1,2})$/,"$1-$2")}

function Transferencias(){
 const navigate=useNavigate();const balance=useBalance();const{beneficiaries,transactions}=useBank();
 const[name,setName]=useState("");const[doc,setDoc]=useState("");const[bank,setBank]=useState<string>(banks[0]);const[branch,setBranch]=useState("");const[acc,setAcc]=useState("");const[amount,setAmount]=useState("");const[date,setDate]=useState("");const[save,setSave]=useState(false);const[error,setError]=useState<string|null>(null);const[review,setReview]=useState(false);const[showBalance,setShowBalance]=useState(true);
 const schedule=useMemo(()=>buildTransferSchedule(beneficiaries.length),[beneficiaries.length]);const value=parseAmount(amount);const internal=bank.startsWith("237");const type=internal?"Entre contas Bradesco":"TED para outro banco";
 const openScheduledReceipt=(beneficiary:(typeof beneficiaries)[number],scheduled:Date)=>{const scheduledDate=`${scheduled.getFullYear()}-${String(scheduled.getMonth()+1).padStart(2,"0")}-${String(scheduled.getDate()).padStart(2,"0")}`;const counterpart=`PARA: ${beneficiary.name}`;const beneficiaryAmount=scheduledAmount(beneficiary.name);let tx=transactions.find(item=>item.category==="transferencia"&&item.status==="Agendado"&&item.counterpart===counterpart&&item.amount===beneficiaryAmount&&item.scheduledFor?.startsWith(scheduledDate));if(!tx)tx=postTx({category:"transferencia",kind:"out",title:"TRANSFERÊNCIA AGENDADA",counterpart,amount:beneficiaryAmount,channel:"App Empresas",status:"Agendado",scheduledFor:new Date(`${scheduledDate}T12:00`).toISOString(),extraRows:[{label:"Tipo",value:beneficiary.bank.startsWith("237")?"Entre contas Bradesco":"Transferência para outro banco"},{label:"Favorecido",value:beneficiary.name},{label:"CPF/CNPJ",value:beneficiary.doc},{label:"Instituição",value:beneficiary.bank},{label:"Agência / Conta",value:`${beneficiary.branch} / ${beneficiary.account}`} ]});void navigate({to:"/app/comprovante/$id",params:{id:tx.id}})};
 const check=()=>{if(date&&!isBusinessDay(new Date(`${date}T12:00:00`)))return setError("Escolha um dia útil. Transferências agendadas não podem cair em finais de semana ou feriados.");if(name.trim().length<3)return setError("Informe o nome do favorecido.");if(doc.replace(/\D/g,"").length<11)return setError("Informe um CPF ou CNPJ válido.");if(!/^\d{4}$/.test(branch))return setError("A agência deve ter 4 números.");if(acc.replace(/\D/g,"").length<4)return setError("Informe a conta com dígito.");if(!Number.isFinite(value)||value<=0)return setError("Informe um valor maior que zero.");if(!date&&value>balance)return setError("Saldo insuficiente.");setError(null);setReview(true)};
 const rows=[{label:"Tipo",value:type},{label:"Favorecido",value:name.trim().toUpperCase()},{label:"CPF/CNPJ",value:doc},{label:"Instituição",value:bank},{label:"Agência / Conta",value:`${branch} / ${acc}`},{label:"Quando",value:date?`Agendado para ${new Date(`${date}T12:00`).toLocaleDateString("pt-BR")}`:"Agora"}];
 const confirm=()=>{if(save)addBeneficiary({name:name.trim().toUpperCase(),doc,bank,branch,account:acc});const tx=postTx({category:"transferencia",kind:"out",title:date?"TRANSFERÊNCIA AGENDADA":internal?"TRANSF. ENTRE CONTAS":"TED ENVIADA",counterpart:`PARA: ${name.trim().toUpperCase()}`,amount:value,channel:"App Empresas",status:date?"Agendado":"Concluído",...(date?{scheduledFor:new Date(`${date}T12:00`).toISOString()}:{}),extraRows:rows,notify:{kind:"transferencia",title:date?"Transferência agendada":"Transferência enviada",body:`${formatBRL(value)} para ${name.trim().toUpperCase()}.`}});void navigate({to:"/app/comprovante/$id",params:{id:tx.id},replace:true})};
 if(review)return <><SubHeader title="Revisar transferência" compactActions/><ConfirmPanel verb="transferência" amount={value} rows={rows} onConfirm={confirm} onBack={()=>setReview(false)}/></>;
 return <><SubHeader title="Transferências" compactActions/><main className="bg-[#f4f5f7] px-3 pb-8 pt-4">
  <section className="rounded-xl border border-[#dedfe3] bg-white p-4 shadow-[0_2px_8px_rgba(0,0,0,.08)]"><p className="text-[11px] font-bold uppercase tracking-wide text-muted-foreground">Conta de origem · ambiente simulado</p><p className="mt-2 text-sm font-bold">{account.company}</p><p className="mt-1 text-xs text-muted-foreground">CNPJ {account.cnpj}</p><div className="mt-4 grid grid-cols-[minmax(0,1fr)_auto] items-end gap-3 border-t border-border pt-4"><div><p className="text-sm text-muted-foreground">Saldo disponível</p><p className="mt-1 text-[clamp(1.65rem,8vw,2.2rem)] font-extrabold tracking-tight tabular-nums">{showBalance?formatBRL(balance):"R$ ••••••••"}</p></div><button type="button" onClick={()=>setShowBalance(v=>!v)} className="grid size-10 place-items-center rounded-full text-[#cc092f]" aria-label="Mostrar ou ocultar saldo"><Eye className="size-6"/></button></div><div className="mt-4 border-t border-border pt-3 text-sm font-medium"><Landmark className="mr-2 inline size-5 text-[#cc092f]"/>Conta corrente: {account.number} · Agência {account.branch}</div></section>

  <section className="mt-3 grid grid-cols-2 gap-2">{[
   {label:"Transferir",icon:Send,action:()=>document.getElementById("new-transfer")?.scrollIntoView({behavior:"smooth"})},
   {label:"Agendar",icon:CalendarDays,action:()=>document.getElementById("transfer-date")?.scrollIntoView({behavior:"smooth",block:"center"})},
   {label:"Meus favorecidos",icon:UsersRound,action:()=>document.getElementById("beneficiaries")?.scrollIntoView({behavior:"smooth"})},
   {label:"Comprovantes",icon:ReceiptText,action:()=>document.getElementById("scheduled-transfers")?.scrollIntoView({behavior:"smooth"})}
  ].map(item=><button key={item.label} type="button" onClick={item.action} className="flex min-h-14 items-center justify-center gap-3 rounded-lg border border-[#dedfe3] bg-white px-3 text-sm font-semibold shadow-[0_2px_6px_rgba(0,0,0,.07)]"><item.icon className="size-5 text-[#b40b2f]"/><span>{item.label}</span></button>)}</section>

  <section id="new-transfer" className="mt-3 rounded-xl border border-[#dedfe3] bg-white p-4 shadow-[0_2px_8px_rgba(0,0,0,.08)]"><h2 className="text-lg font-bold">Dados da transferência</h2><div className="mt-3"><Field label="Beneficiário / Favorecido *" value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do favorecido"/><Field label="CPF ou CNPJ *" value={doc} onChange={e=>setDoc(formatDocument(e.target.value))} inputMode="numeric" placeholder="000.000.000-00"/><SelectField label="Banco *" options={banks} value={bank} onChange={e=>setBank(e.target.value)}/><div className="grid grid-cols-2 gap-3"><Field label="Agência *" value={branch} maxLength={4} onChange={e=>setBranch(e.target.value.replace(/\D/g,""))} inputMode="numeric" placeholder="0000"/><Field label="Conta *" value={acc} onChange={e=>setAcc(e.target.value)} placeholder="000000-0"/></div><Field label="Valor da transferência *" value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="R$ 0,00"/><div id="transfer-date"><Field label="Data da transferência" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={save} onChange={e=>setSave(e.target.checked)} className="size-4 accent-[#cc092f]"/>Salvar como favorecido</label>{error&&<ErrorNote>{error}</ErrorNote>}<button type="button" onClick={check} className="mt-5 w-full rounded-md bg-[#cc092f] px-4 py-3 font-bold text-white shadow-sm">Continuar</button></div></section>

  <section id="beneficiaries" className="mt-3 rounded-xl border border-[#dedfe3] bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold">Meus favorecidos</h2><span className="text-xs font-semibold text-[#b40b2f]">{beneficiaries.length} cadastrados</span></div><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{beneficiaries.slice(0,6).map(b=><button key={b.id} type="button" onClick={()=>{setName(b.name);setDoc(b.doc);setBank(b.bank);setBranch(b.branch);setAcc(b.account);document.getElementById("new-transfer")?.scrollIntoView({behavior:"smooth"})}} className="min-w-[190px] rounded-lg border border-border p-3 text-left"><span className="block truncate text-sm font-semibold">{b.name}</span><span className="mt-1 block truncate text-xs text-muted-foreground">{b.bank}</span></button>)}</div></section>

  <DecemberTransferSchedule beneficiaries={beneficiaries} schedule={schedule} onSelect={(b,s)=>openScheduledReceipt(b,s)}/><div id="scheduled-transfers"><ScheduledList category="transferencia"/></div><p className="mt-5 rounded-lg border border-dashed border-border bg-white p-3 text-center text-[11px] font-medium text-muted-foreground">AMBIENTE SIMULADO · SEM OPERAÇÕES BANCÁRIAS REAIS</p>
 </main></>;
}

export function ScheduledList({category}:{category:"transferencia"|"pagamento"}){const navigate=useNavigate();const{transactions}=useBank();const list=transactions.filter(t=>t.category===category&&(t.status==="Agendado"||t.status==="Cancelado"));if(!list.length)return null;return <section className="mt-4 rounded-xl border border-[#dedfe3] bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold">Transferências agendadas</h2><span className="text-xs font-semibold text-[#b40b2f]">Ver todas</span></div><div className="mt-3 flex gap-5 border-b border-border text-xs font-semibold"><span className="border-b-2 border-[#cc092f] pb-2 text-[#cc092f]">Todos ({list.length})</span><span className="pb-2 text-muted-foreground">Próximos 7 dias</span><span className="pb-2 text-muted-foreground">Este mês</span></div><ul className="divide-y divide-border">{list.map(t=><li key={t.id}><button type="button" onClick={()=>void navigate({to:"/app/comprovante/$id",params:{id:t.id}})} className="grid w-full grid-cols-[minmax(0,1fr)_auto] items-center gap-3 py-3 text-left"><span className="min-w-0"><span className="block truncate text-sm font-semibold">{t.counterpart}</span><span className="block text-xs text-muted-foreground">{t.scheduledFor?formatDay(t.scheduledFor):""} · {t.status}</span></span><span className="text-right"><span className={cn("block text-sm font-bold tabular-nums",t.status==="Cancelado"&&"line-through opacity-60")}>{formatBRL(t.amount)}</span><span className="mt-1 block text-[11px] font-semibold text-[#b40b2f]">Ver detalhes</span></span></button></li>)}</ul></section>}

const nationalHolidays2026=new Set(["2026-01-01","2026-04-21","2026-05-01","2026-09-07","2026-10-12","2026-11-02","2026-11-15","2026-11-20","2026-12-25"]);
function dateKey(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
function isBusinessDay(date:Date){const weekday=date.getDay();return weekday!==0&&weekday!==6&&!nationalHolidays2026.has(dateKey(date))}
function buildTransferSchedule(count:number){const businessDays:Date[]=[];const cursor=new Date(2026,11,1);while(businessDays.length<Math.ceil(count/2)*2){if(isBusinessDay(cursor))businessDays.push(new Date(cursor));cursor.setDate(cursor.getDate()+1)}return businessDays}
function DecemberTransferSchedule({beneficiaries,schedule,onSelect}:{beneficiaries:ReturnType<typeof useBank>["beneficiaries"];schedule:Date[];onSelect:(beneficiary:ReturnType<typeof useBank>["beneficiaries"][number],scheduledDate:Date)=>void}){return <section className="mt-4 rounded-xl border border-[#dedfe3] bg-white p-4 shadow-sm"><h2 className="font-bold">Agendamento de transferência</h2><ul className="mt-2 divide-y divide-border">{beneficiaries.map((b,index)=>{const scheduled=schedule[Math.floor(index/2)*2];if(!scheduled)return null;return <li key={b.id}><button type="button" onClick={()=>onSelect(b,scheduled)} className="flex w-full items-center justify-between gap-3 py-3 text-left"><span className="min-w-0"><span className="block truncate text-sm font-semibold">{b.name}</span><span className="block text-xs text-muted-foreground">{scheduled.toLocaleDateString("pt-BR")} · Agendado</span></span><span className="shrink-0 text-right text-sm font-bold tabular-nums">{formatBRL(scheduledAmount(b.name))}<span className="mt-1 block text-[11px] font-semibold text-[#b40b2f]">Ver comprovante</span></span></button></li>})}</ul></section>}
