/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as RecuperarAcessoRouteImport } from './routes/recuperar-acesso'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCartoesRouteImport } from './routes/app.cartoes'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppComprovantesRouteImport } from './routes/app.comprovantes'
import { Route as AppCreditoRouteImport } from './routes/app.credito'
import { Route as AppExtratoRouteImport } from './routes/app.extrato'
import { Route as AppNotificacoesRouteImport } from './routes/app.notificacoes'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppPixRouteImport } from './routes/app.pix'
import { Route as AppPrivacidadeRouteImport } from './routes/app.privacidade'
import { Route as AppSegurancaRouteImport } from './routes/app.seguranca'
import { Route as AppServicosRouteImport } from './routes/app.servicos'
import { Route as AppComprovanteIdRouteImport } from './routes/app.comprovante.$id'
import { Route as AppContaSlugRouteImport } from './routes/app.conta.$slug'
import { Route as AppPixIndexRouteImport } from './routes/app.pix.index'
import { Route as AppPixChavesRouteImport } from './routes/app.pix.chaves'
import { Route as AppPixEnviarRouteImport } from './routes/app.pix.enviar'
import { Route as AppPixHistoricoRouteImport } from './routes/app.pix.historico'
import { Route as AppPixLimitesRouteImport } from './routes/app.pix.limites'
import { Route as AppPixReceberRouteImport } from './routes/app.pix.receber'
import { Route as AppServicoSlugRouteImport } from './routes/app.servico.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarAcessoRoute = RecuperarAcessoRouteImport.update({
  id: '/recuperar-acesso',
  path: '/recuperar-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesRoute = AppCartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppComprovantesRoute = AppComprovantesRouteImport.update({
  id: '/comprovantes',
  path: '/comprovantes',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditoRoute = AppCreditoRouteImport.update({
  id: '/credito',
  path: '/credito',
  getParentRoute: () => AppRoute,
} as any)
const AppExtratoRoute = AppExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPixRoute = AppPixRouteImport.update({
  id: '/pix',
  path: '/pix',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacidadeRoute = AppPrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => AppRoute,
} as any)
const AppSegurancaRoute = AppSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AppRoute,
} as any)
const AppServicosRoute = AppServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AppRoute,
} as any)
const AppComprovanteIdRoute = AppComprovanteIdRouteImport.update({
  id: '/comprovante/$id',
  path: '/comprovante/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppContaSlugRoute = AppContaSlugRouteImport.update({
  id: '/conta/$slug',
  path: '/conta/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppPixIndexRoute = AppPixIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPixRoute,
} as any)
const AppPixChavesRoute = AppPixChavesRouteImport.update({
  id: '/chaves',
  path: '/chaves',
  getParentRoute: () => AppPixRoute,
} as any)
const AppPixEnviarRoute = AppPixEnviarRouteImport.update({
  id: '/enviar',
  path: '/enviar',
  getParentRoute: () => AppPixRoute,
} as any)
const AppPixHistoricoRoute = AppPixHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppPixRoute,
} as any)
const AppPixLimitesRoute = AppPixLimitesRouteImport.update({
  id: '/limites',
  path: '/limites',
  getParentRoute: () => AppPixRoute,
} as any)
const AppPixReceberRoute = AppPixReceberRouteImport.update({
  id: '/receber',
  path: '/receber',
  getParentRoute: () => AppPixRoute,
} as any)
const AppServicoSlugRoute = AppServicoSlugRouteImport.update({
  id: '/servico/$slug',
  path: '/servico/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/recuperar-acesso': typeof RecuperarAcessoRoute
  '/app/cartoes': typeof AppCartoesRoute
  '/app/chat': typeof AppChatRoute
  '/app/comprovantes': typeof AppComprovantesRoute
  '/app/credito': typeof AppCreditoRoute
  '/app/extrato': typeof AppExtratoRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/pix': typeof AppPixRouteWithChildren
  '/app/privacidade': typeof AppPrivacidadeRoute
  '/app/seguranca': typeof AppSegurancaRoute
  '/app/servicos': typeof AppServicosRoute
  '/app/': typeof AppIndexRoute
  '/app/comprovante/$id': typeof AppComprovanteIdRoute
  '/app/conta/$slug': typeof AppContaSlugRoute
  '/app/pix/chaves': typeof AppPixChavesRoute
  '/app/pix/enviar': typeof AppPixEnviarRoute
  '/app/pix/historico': typeof AppPixHistoricoRoute
  '/app/pix/limites': typeof AppPixLimitesRoute
  '/app/pix/receber': typeof AppPixReceberRoute
  '/app/servico/$slug': typeof AppServicoSlugRoute
  '/app/pix/': typeof AppPixIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recuperar-acesso': typeof RecuperarAcessoRoute
  '/app/cartoes': typeof AppCartoesRoute
  '/app/chat': typeof AppChatRoute
  '/app/comprovantes': typeof AppComprovantesRoute
  '/app/credito': typeof AppCreditoRoute
  '/app/extrato': typeof AppExtratoRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/privacidade': typeof AppPrivacidadeRoute
  '/app/seguranca': typeof AppSegurancaRoute
  '/app/servicos': typeof AppServicosRoute
  '/app': typeof AppIndexRoute
  '/app/comprovante/$id': typeof AppComprovanteIdRoute
  '/app/conta/$slug': typeof AppContaSlugRoute
  '/app/pix/chaves': typeof AppPixChavesRoute
  '/app/pix/enviar': typeof AppPixEnviarRoute
  '/app/pix/historico': typeof AppPixHistoricoRoute
  '/app/pix/limites': typeof AppPixLimitesRoute
  '/app/pix/receber': typeof AppPixReceberRoute
  '/app/servico/$slug': typeof AppServicoSlugRoute
  '/app/pix': typeof AppPixIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/recuperar-acesso': typeof RecuperarAcessoRoute
  '/app/cartoes': typeof AppCartoesRoute
  '/app/chat': typeof AppChatRoute
  '/app/comprovantes': typeof AppComprovantesRoute
  '/app/credito': typeof AppCreditoRoute
  '/app/extrato': typeof AppExtratoRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/pix': typeof AppPixRouteWithChildren
  '/app/privacidade': typeof AppPrivacidadeRoute
  '/app/seguranca': typeof AppSegurancaRoute
  '/app/servicos': typeof AppServicosRoute
  '/app/': typeof AppIndexRoute
  '/app/comprovante/$id': typeof AppComprovanteIdRoute
  '/app/conta/$slug': typeof AppContaSlugRoute
  '/app/pix/chaves': typeof AppPixChavesRoute
  '/app/pix/enviar': typeof AppPixEnviarRoute
  '/app/pix/historico': typeof AppPixHistoricoRoute
  '/app/pix/limites': typeof AppPixLimitesRoute
  '/app/pix/receber': typeof AppPixReceberRoute
  '/app/servico/$slug': typeof AppServicoSlugRoute
  '/app/pix/': typeof AppPixIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/recuperar-acesso'
    | '/app/cartoes'
    | '/app/chat'
    | '/app/comprovantes'
    | '/app/credito'
    | '/app/extrato'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/pix'
    | '/app/privacidade'
    | '/app/seguranca'
    | '/app/servicos'
    | '/app/'
    | '/app/comprovante/$id'
    | '/app/conta/$slug'
    | '/app/pix/chaves'
    | '/app/pix/enviar'
    | '/app/pix/historico'
    | '/app/pix/limites'
    | '/app/pix/receber'
    | '/app/servico/$slug'
    | '/app/pix/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recuperar-acesso'
    | '/app/cartoes'
    | '/app/chat'
    | '/app/comprovantes'
    | '/app/credito'
    | '/app/extrato'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/privacidade'
    | '/app/seguranca'
    | '/app/servicos'
    | '/app'
    | '/app/comprovante/$id'
    | '/app/conta/$slug'
    | '/app/pix/chaves'
    | '/app/pix/enviar'
    | '/app/pix/historico'
    | '/app/pix/limites'
    | '/app/pix/receber'
    | '/app/servico/$slug'
    | '/app/pix'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/recuperar-acesso'
    | '/app/cartoes'
    | '/app/chat'
    | '/app/comprovantes'
    | '/app/credito'
    | '/app/extrato'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/pix'
    | '/app/privacidade'
    | '/app/seguranca'
    | '/app/servicos'
    | '/app/'
    | '/app/comprovante/$id'
    | '/app/conta/$slug'
    | '/app/pix/chaves'
    | '/app/pix/enviar'
    | '/app/pix/historico'
    | '/app/pix/limites'
    | '/app/pix/receber'
    | '/app/servico/$slug'
    | '/app/pix/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  RecuperarAcessoRoute: typeof RecuperarAcessoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-acesso': {
      id: '/recuperar-acesso'
      path: '/recuperar-acesso'
      fullPath: '/recuperar-acesso'
      preLoaderRoute: typeof RecuperarAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cartoes': {
      id: '/app/cartoes'
      path: '/cartoes'
      fullPath: '/app/cartoes'
      preLoaderRoute: typeof AppCartoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comprovantes': {
      id: '/app/comprovantes'
      path: '/comprovantes'
      fullPath: '/app/comprovantes'
      preLoaderRoute: typeof AppComprovantesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/credito': {
      id: '/app/credito'
      path: '/credito'
      fullPath: '/app/credito'
      preLoaderRoute: typeof AppCreditoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/extrato': {
      id: '/app/extrato'
      path: '/extrato'
      fullPath: '/app/extrato'
      preLoaderRoute: typeof AppExtratoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificacoes': {
      id: '/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pix': {
      id: '/app/pix'
      path: '/pix'
      fullPath: '/app/pix'
      preLoaderRoute: typeof AppPixRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/privacidade': {
      id: '/app/privacidade'
      path: '/privacidade'
      fullPath: '/app/privacidade'
      preLoaderRoute: typeof AppPrivacidadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seguranca': {
      id: '/app/seguranca'
      path: '/seguranca'
      fullPath: '/app/seguranca'
      preLoaderRoute: typeof AppSegurancaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/servicos': {
      id: '/app/servicos'
      path: '/servicos'
      fullPath: '/app/servicos'
      preLoaderRoute: typeof AppServicosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comprovante/$id': {
      id: '/app/comprovante/$id'
      path: '/comprovante/$id'
      fullPath: '/app/comprovante/$id'
      preLoaderRoute: typeof AppComprovanteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conta/$slug': {
      id: '/app/conta/$slug'
      path: '/conta/$slug'
      fullPath: '/app/conta/$slug'
      preLoaderRoute: typeof AppContaSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pix/': {
      id: '/app/pix/'
      path: '/'
      fullPath: '/app/pix/'
      preLoaderRoute: typeof AppPixIndexRouteImport
      parentRoute: typeof AppPixRoute
    }
    '/app/pix/chaves': {
      id: '/app/pix/chaves'
      path: '/chaves'
      fullPath: '/app/pix/chaves'
      preLoaderRoute: typeof AppPixChavesRouteImport
      parentRoute: typeof AppPixRoute
    }
    '/app/pix/enviar': {
      id: '/app/pix/enviar'
      path: '/enviar'
      fullPath: '/app/pix/enviar'
      preLoaderRoute: typeof AppPixEnviarRouteImport
      parentRoute: typeof AppPixRoute
    }
    '/app/pix/historico': {
      id: '/app/pix/historico'
      path: '/historico'
      fullPath: '/app/pix/historico'
      preLoaderRoute: typeof AppPixHistoricoRouteImport
      parentRoute: typeof AppPixRoute
    }
    '/app/pix/limites': {
      id: '/app/pix/limites'
      path: '/limites'
      fullPath: '/app/pix/limites'
      preLoaderRoute: typeof AppPixLimitesRouteImport
      parentRoute: typeof AppPixRoute
    }
    '/app/pix/receber': {
      id: '/app/pix/receber'
      path: '/receber'
      fullPath: '/app/pix/receber'
      preLoaderRoute: typeof AppPixReceberRouteImport
      parentRoute: typeof AppPixRoute
    }
    '/app/servico/$slug': {
      id: '/app/servico/$slug'
      path: '/servico/$slug'
      fullPath: '/app/servico/$slug'
      preLoaderRoute: typeof AppServicoSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppPixRouteChildren {
  AppPixChavesRoute: typeof AppPixChavesRoute
  AppPixEnviarRoute: typeof AppPixEnviarRoute
  AppPixHistoricoRoute: typeof AppPixHistoricoRoute
  AppPixLimitesRoute: typeof AppPixLimitesRoute
  AppPixReceberRoute: typeof AppPixReceberRoute
  AppPixIndexRoute: typeof AppPixIndexRoute
}

const AppPixRouteChildren: AppPixRouteChildren = {
  AppPixChavesRoute: AppPixChavesRoute,
  AppPixEnviarRoute: AppPixEnviarRoute,
  AppPixHistoricoRoute: AppPixHistoricoRoute,
  AppPixLimitesRoute: AppPixLimitesRoute,
  AppPixReceberRoute: AppPixReceberRoute,
  AppPixIndexRoute: AppPixIndexRoute,
}

const AppPixRouteWithChildren =
  AppPixRoute._addFileChildren(AppPixRouteChildren)

interface AppRouteChildren {
  AppCartoesRoute: typeof AppCartoesRoute
  AppChatRoute: typeof AppChatRoute
  AppComprovantesRoute: typeof AppComprovantesRoute
  AppCreditoRoute: typeof AppCreditoRoute
  AppExtratoRoute: typeof AppExtratoRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPixRoute: typeof AppPixRouteWithChildren
  AppPrivacidadeRoute: typeof AppPrivacidadeRoute
  AppSegurancaRoute: typeof AppSegurancaRoute
  AppServicosRoute: typeof AppServicosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppComprovanteIdRoute: typeof AppComprovanteIdRoute
  AppContaSlugRoute: typeof AppContaSlugRoute
  AppServicoSlugRoute: typeof AppServicoSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCartoesRoute: AppCartoesRoute,
  AppChatRoute: AppChatRoute,
  AppComprovantesRoute: AppComprovantesRoute,
  AppCreditoRoute: AppCreditoRoute,
  AppExtratoRoute: AppExtratoRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPixRoute: AppPixRouteWithChildren,
  AppPrivacidadeRoute: AppPrivacidadeRoute,
  AppSegurancaRoute: AppSegurancaRoute,
  AppServicosRoute: AppServicosRoute,
  AppIndexRoute: AppIndexRoute,
  AppComprovanteIdRoute: AppComprovanteIdRoute,
  AppContaSlugRoute: AppContaSlugRoute,
  AppServicoSlugRoute: AppServicoSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  RecuperarAcessoRoute: RecuperarAcessoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
