/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppExtratoRouteImport } from './routes/app.extrato'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppServicosRouteImport } from './routes/app.servicos'
import { Route as AppContaSlugRouteImport } from './routes/app.conta.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppExtratoRoute = AppExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppServicosRoute = AppServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AppRoute,
} as any)
const AppContaSlugRoute = AppContaSlugRouteImport.update({
  id: '/conta/$slug',
  path: '/conta/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/chat': typeof AppChatRoute
  '/app/extrato': typeof AppExtratoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/servicos': typeof AppServicosRoute
  '/app/': typeof AppIndexRoute
  '/app/conta/$slug': typeof AppContaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/chat': typeof AppChatRoute
  '/app/extrato': typeof AppExtratoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/servicos': typeof AppServicosRoute
  '/app': typeof AppIndexRoute
  '/app/conta/$slug': typeof AppContaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/chat': typeof AppChatRoute
  '/app/extrato': typeof AppExtratoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/servicos': typeof AppServicosRoute
  '/app/': typeof AppIndexRoute
  '/app/conta/$slug': typeof AppContaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/chat'
    | '/app/extrato'
    | '/app/perfil'
    | '/app/servicos'
    | '/app/'
    | '/app/conta/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/chat'
    | '/app/extrato'
    | '/app/perfil'
    | '/app/servicos'
    | '/app'
    | '/app/conta/$slug'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/chat'
    | '/app/extrato'
    | '/app/perfil'
    | '/app/servicos'
    | '/app/'
    | '/app/conta/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/extrato': {
      id: '/app/extrato'
      path: '/extrato'
      fullPath: '/app/extrato'
      preLoaderRoute: typeof AppExtratoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/servicos': {
      id: '/app/servicos'
      path: '/servicos'
      fullPath: '/app/servicos'
      preLoaderRoute: typeof AppServicosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conta/$slug': {
      id: '/app/conta/$slug'
      path: '/conta/$slug'
      fullPath: '/app/conta/$slug'
      preLoaderRoute: typeof AppContaSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppExtratoRoute: typeof AppExtratoRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppServicosRoute: typeof AppServicosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppContaSlugRoute: typeof AppContaSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppExtratoRoute: AppExtratoRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppServicosRoute: AppServicosRoute,
  AppIndexRoute: AppIndexRoute,
  AppContaSlugRoute: AppContaSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
